#!/usr/bin/env bash
# Regenerate the nginx snippets that describe Cloudflare's edge IP ranges.
#
#   sudo /var/www/cafe/deploy/cloudflare/update-cloudflare-ips.sh
#
# Writes /etc/nginx/snippets/cloudflare-real-ip.conf: set_real_ip_from plus
# real_ip_header, so logs show the visitor's address instead of Cloudflare's.
#
# It deliberately does NOT generate an nginx allow/deny list for "only accept
# Cloudflare". nginx evaluates allow/deny against $remote_addr AFTER the realip
# module has rewritten it to the visitor's IP, so a Cloudflare-only allow-list
# rejects every genuine visitor and takes the site down. Lock the origin down
# with Authenticated Origin Pulls (mTLS) instead — see deploy/DEPLOYMENT.md.
#
# Cloudflare adds ranges occasionally, so run this monthly from cron:
#   0 4 1 * * /var/www/cafe/deploy/cloudflare/update-cloudflare-ips.sh >/dev/null
#
# The ranges are never hardcoded in this repo: a stale allow-list would lock
# you out of your own server. They are always fetched live.
set -euo pipefail

V4_URL="${CF_V4_URL:-https://www.cloudflare.com/ips-v4}"
V6_URL="${CF_V6_URL:-https://www.cloudflare.com/ips-v6}"
SNIPPET_DIR="${SNIPPET_DIR:-/etc/nginx/snippets}"
REAL_IP_FILE="$SNIPPET_DIR/cloudflare-real-ip.conf"
RELOAD="${RELOAD:-1}"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "==> Fetching Cloudflare ranges"
curl -fsS --max-time 30 "$V4_URL" -o "$tmp/v4"
curl -fsS --max-time 30 "$V6_URL" -o "$tmp/v6"

# Refuse to write anything unless every line looks like a CIDR. A truncated
# download or a captive-portal HTML page must not become nginx config.
validate() {
  local file="$1" label="$2" pattern="$3" count
  count="$(grep -cE "$pattern" "$file" || true)"
  if [ "$count" -lt 1 ]; then
    echo "ERROR: no valid $label ranges in the response from Cloudflare." >&2
    head -3 "$file" >&2
    exit 1
  fi
  if [ "$count" -ne "$(grep -cve '^[[:space:]]*$' "$file")" ]; then
    echo "ERROR: $label response contains lines that are not CIDRs." >&2
    exit 1
  fi
  echo "    $count $label ranges"
}
validate "$tmp/v4" IPv4 '^[0-9]{1,3}(\.[0-9]{1,3}){3}/[0-9]{1,2}$'
validate "$tmp/v6" IPv6 '^[0-9a-fA-F:]+/[0-9]{1,3}$'

stamp="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

{
  echo "# Generated by deploy/cloudflare/update-cloudflare-ips.sh on $stamp"
  echo "# Do not edit by hand; re-run the script instead."
  echo
  while read -r cidr; do [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"; done < "$tmp/v4"
  while read -r cidr; do [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"; done < "$tmp/v6"
  echo
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "$tmp/real-ip.conf"

mkdir -p "$SNIPPET_DIR"
[ -f "$REAL_IP_FILE" ] && cp "$REAL_IP_FILE" "$REAL_IP_FILE.bak"
cp "$tmp/real-ip.conf" "$REAL_IP_FILE"
echo "==> Wrote $REAL_IP_FILE"

if [ "$RELOAD" = "1" ]; then
  if nginx -t 2>/dev/null; then
    nginx -s reload
    echo "==> nginx reloaded"
  else
    echo "ERROR: nginx -t failed with the new snippet; rolling back." >&2
    [ -f "$REAL_IP_FILE.bak" ] && mv "$REAL_IP_FILE.bak" "$REAL_IP_FILE"
    nginx -t >&2
    exit 1
  fi
fi
